---

- name: Ensure the standard locale exists
  community.general.locale_gen:
    name: '{{ standard_locale }}'
    state: present

- name: Change hostname to FQDN without domain
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'
    use: systemd
  ignore_errors: true

- name: Add the ansible user "ansible" with a bash shell, appending the group 'sudo' to the user's groups
  ansible.builtin.user:
    name: ansible
    password: '{{ ansible_pwd | password_hash("sha512") }}'
    shell: /bin/bash
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

- name: Change the root user password
  ansible.builtin.user:
    name: root
    password: '{{ "{{ inventory_hostname }}root" | password_hash("sha512") }}'

- name: Make sure line is in /etc/sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^ansible '
    line: 'ansible    ALL = (ALL) NOPASSWD: ALL'

- name: Ensure root ssh access is set 'no'
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'

#- name: Register user ansible's public key on remote machines
#  ansible.builtin.slurp:
#    src: /home/ansible/.ssh/id_rsa.pub
#  register: '"{{ inventory_hostname }}".id_rsa.pub'

- name: Setup multiple authorized keys
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/apollo-tycho
    - public_keys/heimdall-ansible
    - public_keys/freya-tycho
    - public_keys/M2729-doctert
    - public_keys/zeus-tycho

...
